version: '3.8'

services:
  db:
    environment:
      - PGDATA= /var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
    image: postgres
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data/pgdata

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=dev.settings.dev
    env_file: .dockerenv
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db

#For debugging purposes, maybe consider using the below container
# You can run it with docker-compose up bash (with the db etc. up) 
# And then use docker exec -it <container_name> bash to bash into it and try running stuff
  bash:
    build: .
    command: /bin/sh -c "while true; do sleep 5; date; done"
    env_file: .dockerenv
    volumes:
      - .:/code
    ports:
      - "8000:8001"
    depends_on:
      - db
#Note, when you move to microservices, look up external networks, you can actually configure
# one network for a specific project and then have containers from other proejcts talk to the same network
# useful when you have many projects that are supposed to have components talking to each other.
networks:
  default:
    driver: bridge
