export DEBUG=True
export DATABASE_ENGINE='django.db.backends.postgresql'
export DATABASE_NAME='django'
export DATABASE_USER='postgres'
export DATABASE_PASSWORD='postgres' #TODO set on postgres instanc
export DATABASE_HOST='localhost'
export DATABASE_PORT='5432'
export SECRET_KEY='fsgsweoriqwevnzasdf43'
export USER_ID='vc'
