# Generated by Django 3.1.2 on 2020-10-19 17:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default='docker', max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default='docker', max_length=20)),
                ('ID', models.UUIDField(db_column='scenario_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_number', models.IntegerField(db_column='scenario_number')),
                ('item', models.TextField(db_column='item')),
                ('cost', models.IntegerField(db_column='cost')),
                ('verbiage', models.TextField(db_column='verbiage')),
            ],
            options={
                'db_table': 'scenario',
            },
        ),
    ]
